In [14]:
import pandas as pd
import os
import numpy as np
import glob

from sklearn.metrics import f1_score


import warnings
warnings.filterwarnings("ignore")

In [13]:
#Target = Category --> Classification
#Struktur id= Year-Month-Day
sample = pd.read_csv("C:/Users/visco/Downloads/penyisihan-datavidia-10/sample_submission.csv")
sample.head()

                id  category
0  2025-09-01_DKI1       NaN
1  2025-09-01_DKI2       NaN
2  2025-09-01_DKI3       NaN
3  2025-09-01_DKI4       NaN
4  2025-09-01_DKI5       NaN

In [12]:
#Car dataset kolom category
#misal
ispu_2024= pd.read_csv("C:/Users/visco/Downloads/penyisihan-datavidia-10/ISPU/data-indeks-standar-pencemar-udara-(ispu)-di-provinsi-dki-jakarta-komponen-data-2024.csv")
ispu_2024.columns
ispu_2024.head()

,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max,parameter_pencemar_kritis,kategori
0,202401,1,21,DKI3 Jagakarsa,51.0,65.0,45.0,9.0,8.0,79.0,79.0,NaN,SEDANG
1,202401,1,22,DKI3 Jagakarsa,27.0,34.0,45.0,5.0,8.0,56.0,56.0,NaN,SEDANG
2,202401,1,23,DKI3 Jagakarsa,NaN,52.0,46.0,6.0,9.0,51.0,52.0,PM25,SEDANG
3,202401,1,24,DKI3 Jagakarsa,46.0,65.0,46.0,8.0,9.0,38.0,65.0,PM25,SEDANG
4,202401,1,25,DKI3 Jagakarsa,37.0,55.0,47.0,7.0,11.0,28.0,55.0,PM25,SEDANG

In [22]:
#Gabung dataset ISPU
files = glob.glob("C:/Users/visco/Downloads/penyisihan-datavidia-10/ISPU/*")

dfs = []
for file in files:
    df = pd.read_csv(file)
    dfs.append(df)

ispu_all = pd.concat(dfs, ignore_index=True)
ispu_all.columns
# ispu_all['kategori'].value_counts()

Index(['periode_data', 'tanggal', 'stasiun', 'pm_sepuluh', 'pm_duakomalima',
       'sulfur_dioksida', 'karbon_monoksida', 'ozon', 'nitrogen_dioksida',
       'max', 'parameter_pencemar_kritis', 'kategori', 'bulan', 'pm10', 'so2',
       'co', 'o3', 'no2', 'critical', 'categori', 'lokasi_spku', 'pm25',
       'pm_10'],
      dtype='object')

In [24]:
use_cols = [
    'pm_sepuluh',
    'pm_duakomalima',
    'sulfur_dioksida',
    'karbon_monoksida',
    'ozon',
    'nitrogen_dioksida',
    'stasiun',
    'kategori'
]

df = ispu_all[use_cols].copy()
df.head()

,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,stasiun,kategori
0,35,-,13,12,31,18,DKI5 Kebon Jeruk Jakarta Barat,BAIK
1,23,-,14,9,32,11,DKI5 Kebon Jeruk Jakarta Barat,BAIK
2,20,-,13,8,33,13,DKI5 Kebon Jeruk Jakarta Barat,BAIK
3,30,-,21,11,28,18,DKI5 Kebon Jeruk Jakarta Barat,BAIK
4,38,44,50,8,19,27,DKI1 Bunderan HI,BAIK

In [25]:
#data cleaning target
df = df[df['kategori'] != 'TIDAK ADA DATA']
df['kategori'].value_counts()

kategori
SEDANG                3684
BAIK                   617
TIDAK SEHAT            526
SANGAT TIDAK SEHAT       4
Name: count, dtype: int64

In [26]:
#HANDLE '-' Value
df.replace('-', np.nan, inplace=True)
df.head()

,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,stasiun,kategori
0,35,NaN,13,12,31,18,DKI5 Kebon Jeruk Jakarta Barat,BAIK
1,23,NaN,14,9,32,11,DKI5 Kebon Jeruk Jakarta Barat,BAIK
2,20,NaN,13,8,33,13,DKI5 Kebon Jeruk Jakarta Barat,BAIK
3,30,NaN,21,11,28,18,DKI5 Kebon Jeruk Jakarta Barat,BAIK
4,38,44,50,8,19,27,DKI1 Bunderan HI,BAIK

In [ ]:
#lihat kolom